### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by ChewbaccaJerky** [ChewbaccaJerky/hoot#2]

**Comment by dallashall** [comment]
@ChewbaccaJerky 
Before I pass this off, I need to see the following:
- [x] Display errors when signing in with bad credentials.
- [x] Make the whole 'Login' Button clickable (currently only the text is clickable)
- [x] Landing page should have both a Sign Up and a Login button.

**Comment by dallashall** [comment]
Last thing:

The cursor should be a pointer on all buttons.
